### ISSUE TITLE
Overlap of map tracker nodes for GC Shop and Medigoron Check

### ISSUE THREAD

**Issue by tnt175** [Hamsda/EmoTrackerPacks#100]
The difference between the coordonates of both nodes are so small (like a pixel or 2 on the y) that the goron city shop node nearly cover the medigoron shop one completely. This can be problematic for those of us who play with both shopsanity and the new expensive merchant option.

**Comment by Hamsda** [comment]
Thanks for the report!
I've been working on getting overworld checks ready for the ER tracker in the past 2 months or so, and will clean up some positioning problems for either map variant in the near future.
