### ISSUE TITLE
please make lax cs chest setting

### ISSUE THREAD

**Issue by Alaszun** [Hamsda/EmoTrackerPacks#112]
Hi sorry for bad englando

so yesterday I was playing flute of tempo switchizer and saw green dot on tracker in building of time 

I play like I always do and follow green dot so go to building of time but cannot find item so green dot is lying to me

I do much research why and seems like was playing new style "S4" seed where the skeleton key to dorf fortress is in that spot instead

Please provide option to play with the lax cs so I can continue to go brrr from green dot

No but seriously please provide the option so we can control visibility of LACS check.

**Comment by Hamsda** [comment]
send help
