### ISSUE TITLE
Meaning color in github markdown

### ISSUE THREAD

**Issue by P-Storm** [Hamsda/EmoTrackerPacks#121]
Hi!

I was looking into the colors and what they mean, but couldn't find it here.

* Green: Can be aquired
* Yellow: You can get this item with logical tricks or glitches.
* Orange: Some but not all in location can be gotten.
* Blue: You can see what it is, but not access it.
* Red: Can't be 

So can you please add these in the [Readme.md] file?

**Comment by Hamsda** [comment]
Yeah, that is how it works. 
Though this is general EmoTracker usage and has nothing to do with my pack specifically. I'd refer you to the FAQ channel on the EmoTracker discord for that.
