### ISSUE TITLE
Add option for fire arrow shadow temple entrance skip

### ISSUE THREAD

**Issue by glentakahashi** [Hamsda/EmoTrackerPacks#81]
Would you accept a PR to add an option for turning the shadow temple no din's fire skip on/off?
https://github.com/TestRunnerSRL/OoT-Randomizer/blob/Dev/SettingsList.py#L958

**Comment by Hamsda** [comment]
I am turning a lot of those into actual options at the moment, so should be coming once real life is a bit more quiet.

**Comment by Hamsda** [comment]
Added in d1125d78b267b74d59ffe5bb8afef44a4c7c7e31
If the trick is on, it will show with the corresponding items, otherwise it won't even show as a sequence break, since it is not allowed in the standard racing rules
